- name: Rustify
  hosts: localhost
  become: no
  gather_facts: yes
  vars:
    package_map:
      centos:
        - curl
        - cmake
        - git
        - gcc

      ubuntu:
        - curl
        - build-essential
        - cmake

      Fedora:
        - curl
        - cmake
        - git
        - gcc
        - util-linux-user

  tasks:
    - name: Install dependent packages
      package:
        name: "{{ package_name }}"
        state: present
      loop: "{{ package_map[ansible_distribution] }}"
      loop_control:
        loop_var: package_name
      become: yes
      become_user: root

    - name: Download and run rustup installer
      shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Install Rust Packages
      community.general.cargo:
        name: "{{ item }}"
        state: present
      with_items:
        - bat
        - starship
        - exa
        - bottom
        - ripgrep
        - nushell


